/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ConsoleAnalyticsRouteImport } from './routes/_console.analytics'
import { Route as ConsoleDashboardRouteImport } from './routes/_console.dashboard'
import { Route as ConsoleProfileRouteImport } from './routes/_console.profile'
import { Route as ConsoleResponsesRouteImport } from './routes/_console.responses'
import { Route as ConsoleSettingsRouteImport } from './routes/_console.settings'
import { Route as ConsoleSurveysIndexRouteImport } from './routes/_console.surveys.index'
import { Route as ConsoleSurveysSurveyIdRouteImport } from './routes/_console.surveys.$surveyId'
import { Route as ConsoleSurveysNewRouteImport } from './routes/_console.surveys.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleAnalyticsRoute = ConsoleAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDashboardRoute = ConsoleDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleProfileRoute = ConsoleProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleResponsesRoute = ConsoleResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSurveysIndexRoute = ConsoleSurveysIndexRouteImport.update({
  id: '/surveys/',
  path: '/surveys/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSurveysSurveyIdRoute = ConsoleSurveysSurveyIdRouteImport.update({
  id: '/surveys/$surveyId',
  path: '/surveys/$surveyId',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSurveysNewRoute = ConsoleSurveysNewRouteImport.update({
  id: '/surveys/new',
  path: '/surveys/new',
  getParentRoute: () => ConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics': typeof ConsoleAnalyticsRoute
  '/dashboard': typeof ConsoleDashboardRoute
  '/profile': typeof ConsoleProfileRoute
  '/responses': typeof ConsoleResponsesRoute
  '/settings': typeof ConsoleSettingsRoute
  '/surveys/$surveyId': typeof ConsoleSurveysSurveyIdRoute
  '/surveys/new': typeof ConsoleSurveysNewRoute
  '/surveys/': typeof ConsoleSurveysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics': typeof ConsoleAnalyticsRoute
  '/dashboard': typeof ConsoleDashboardRoute
  '/profile': typeof ConsoleProfileRoute
  '/responses': typeof ConsoleResponsesRoute
  '/settings': typeof ConsoleSettingsRoute
  '/surveys/$surveyId': typeof ConsoleSurveysSurveyIdRoute
  '/surveys/new': typeof ConsoleSurveysNewRoute
  '/surveys': typeof ConsoleSurveysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_console': typeof ConsoleRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_console/analytics': typeof ConsoleAnalyticsRoute
  '/_console/dashboard': typeof ConsoleDashboardRoute
  '/_console/profile': typeof ConsoleProfileRoute
  '/_console/responses': typeof ConsoleResponsesRoute
  '/_console/settings': typeof ConsoleSettingsRoute
  '/_console/surveys/$surveyId': typeof ConsoleSurveysSurveyIdRoute
  '/_console/surveys/new': typeof ConsoleSurveysNewRoute
  '/_console/surveys/': typeof ConsoleSurveysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/analytics'
    | '/dashboard'
    | '/profile'
    | '/responses'
    | '/settings'
    | '/surveys/$surveyId'
    | '/surveys/new'
    | '/surveys/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/analytics'
    | '/dashboard'
    | '/profile'
    | '/responses'
    | '/settings'
    | '/surveys/$surveyId'
    | '/surveys/new'
    | '/surveys'
  id:
    | '__root__'
    | '/'
    | '/_console'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_console/analytics'
    | '/_console/dashboard'
    | '/_console/profile'
    | '/_console/responses'
    | '/_console/settings'
    | '/_console/surveys/$surveyId'
    | '/_console/surveys/new'
    | '/_console/surveys/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/analytics': {
      id: '/_console/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ConsoleAnalyticsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/dashboard': {
      id: '/_console/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ConsoleDashboardRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/profile': {
      id: '/_console/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ConsoleProfileRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/responses': {
      id: '/_console/responses'
      path: '/responses'
      fullPath: '/responses'
      preLoaderRoute: typeof ConsoleResponsesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/settings': {
      id: '/_console/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/surveys/': {
      id: '/_console/surveys/'
      path: '/surveys'
      fullPath: '/surveys/'
      preLoaderRoute: typeof ConsoleSurveysIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/surveys/$surveyId': {
      id: '/_console/surveys/$surveyId'
      path: '/surveys/$surveyId'
      fullPath: '/surveys/$surveyId'
      preLoaderRoute: typeof ConsoleSurveysSurveyIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/surveys/new': {
      id: '/_console/surveys/new'
      path: '/surveys/new'
      fullPath: '/surveys/new'
      preLoaderRoute: typeof ConsoleSurveysNewRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleAnalyticsRoute: typeof ConsoleAnalyticsRoute
  ConsoleDashboardRoute: typeof ConsoleDashboardRoute
  ConsoleProfileRoute: typeof ConsoleProfileRoute
  ConsoleResponsesRoute: typeof ConsoleResponsesRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleSurveysSurveyIdRoute: typeof ConsoleSurveysSurveyIdRoute
  ConsoleSurveysNewRoute: typeof ConsoleSurveysNewRoute
  ConsoleSurveysIndexRoute: typeof ConsoleSurveysIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleAnalyticsRoute: ConsoleAnalyticsRoute,
  ConsoleDashboardRoute: ConsoleDashboardRoute,
  ConsoleProfileRoute: ConsoleProfileRoute,
  ConsoleResponsesRoute: ConsoleResponsesRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleSurveysSurveyIdRoute: ConsoleSurveysSurveyIdRoute,
  ConsoleSurveysNewRoute: ConsoleSurveysNewRoute,
  ConsoleSurveysIndexRoute: ConsoleSurveysIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
